name: Run Tests on Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  run_tests_on_pull_request:
    env:
      DISPLAY: ":0"
      FORCE_COLOR: "true"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Virtual Frame Buffer Package(xvfb)
        run: sudo apt-get install xvfb
      - name: Create Virtual Display for ChromeDriver to Use
        run: Xvfb :0 -screen 0 1024x768x16 &
      - name: Install Node Dependencies
        run: npm install
      - name: Create rebabel_convert executable
        shell: bash
        run: .github/scripts/create_rebabel_convert_executable
      - name: Make
        run: npm run make
      - name: Test
        run: npm run test:local
